//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aenima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int serial_nr { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public System.DateTime end_date { get; set; }
        public int rent_time { get; set; }
        public int price { get; set; }
        public int equipment_code { get; set; }
        public int employer_number { get; set; }
        public int client_code { get; set; }
        public string active { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
