//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aenima
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentPrice
    {
        public int fare_id { get; set; }
        public System.DateTime validity { get; set; }
        public int price { get; set; }
        public int C_time { get; set; }
        public string name_type { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
